config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/sindex', to: 'users#sindex'
  
  # ログイン情報
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/overtime_application'
      patch 'attendances/update_overtime'
      get 'attendances/overtime_application_approval'
      patch 'attendances/update_overtime_approval'
      patch 'attendances/update_attendances_application'
      get 'attendances/attendances_application_approval'
      patch 'attendances/update_attendances_application_approval'
      patch 'attendances/update_attendances_change'
      get 'attendances/attendances_change_approval'
      patch 'attendances/update_attendances_change_approval'
      get 'attendances/attendances_change_history_log'
    end
    resources :attendances, only: [:update]
    collection { post :import }
  end

  resources :base_points
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/base_point.rb
class BasePoint < ApplicationRecord
end

app/controllers/base_points_controller.rb
class BasePointsController < ApplicationController
  before_action :set_base_point, only: [:destroy, :update, :edit]
  before_action :admin_user, only:[:destroy, :index, :new, :edit, ]

  def index
    
    @base_points = BasePoint.all
  end

  def new
    @base_point = BasePoint.new
  end

  def create
    @base_point = BasePoint.new(base_point_params)
    if @base_point.save
      flash[:success] ="拠点情報を追加しました。"
    else
      flash[:denger] ="拠点情報の追加に失敗しました。"
    end
      redirect_to base_points_url
  end

  def edit
    
  end

  def update
    if @base_point.update_attributes(base_point_params)
      flash[:success] ="拠点情報を更新しました。"
    else
      flash[:denger] ="拠点情報の更新に失敗しました。"
    end
    redirect_to base_points_url
  end

  def destroy
    if @base_point.destroy
    flash[:success] = "拠点情報を削除しました。"
    else
    flash[:danger] = "拠点情報の削除に失敗しました。"
    end
    redirect_to base_points_url
  end

  private
  def set_base_point
    @base_point = BasePoint.find(params[:id])
  end

  def base_point_params
    params.require(:base_point).permit(:base_point_name, :base_point_number, :base_point_type)
  end

end

app/helpers/base_point_helper.rb
module BasePointHelper
end

app/views/base_points/edit.html.erb
<% provide(:title , "BasePointEdit") %>
<% provide(:class_text, 'base_point--edit') %>
<% provide(:button_text, '更新') %>
<h1>拠点情報の更新</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @base_point, local: true) do |f| %>
            <%#= render 'shared/error_messages' %>
            
            <%= f.label :base_point_number, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :base_point_number, class: "form-control" %>
            
            <%= f.label :base_point_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :base_point_name, class: "form-control" %>
            
            <%= f.label :base_point_type, class: "label-#{yield(:class_text)}" %><br />
            <%= f.select :base_point_type,[["出勤中"],["退勤"]] ,class: "form-control" %>
            
            <%= f.submit "#{yield(:button_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
        <% end %>
    </div>
</div>

app/views/base_points/index.html.erb
<% provide(:title, 'Base point') %>
<h1>拠点一覧</h1>
<div class="col-md-12">
    <table class="table table-bordered table-condensed table-hover" id="table-base">
        <thead>
            <tr>
                <th colspan="2" width="40%"></th>
                <th>
                    <%#= User.human_attribute_name :name %>
                    拠点番号
                </th>
                <th>
                    拠点名
                </th>
                <th>
                    勤怠種類
                </th>
            </tr>
        </thead>
        
        <% @base_points.each do |base_point| %>
            <tr>
                <td><%= link_to "修正", edit_base_point_path(base_point), class: "btn btn-primary" %></td>
                <td><%= link_to "削除", base_point, method: :delete, data: { confirm: "拠点番号#{base_point.base_point_number}を削除してもよろしいですか？"}, class: "btn btn-primary" %><%#= base_point.id %></td>
                <td style="text-align:center;">
                    <%= base_point.base_point_number %>
                    <%# if current_user.admin? && !current_user?(user) %> <!-- | --> 
                        <%# link_to "基本情報編集", edit_basic_info_user_path(user) %> <!--| --> 
                        <%# link_to "削除" , user, method: :delete, data: { confirm: "削除してもよろしいですか？"} %>
                    <%# end %>
                </td>
                <td style="text-align:center;">
                    <%= base_point.base_point_name %>
                </td>
                <td style="text-align:center;">
                    <%= base_point.base_point_type %>
                </td>
            </tr>
        <% end %>
        </table>
        <table class="table table-bordered table-condensed table-hover" id="table-base">
        <tr>
        <td colspan="5">
        <%= link_to "拠点情報追加" , new_base_point_path, class: "btn btn-primary btn-lg" %>
        </td>
        </tr>
    </table>
</div>

app/views/base_points/new.html.erb
<% provide(:title, '拠点情報追加') %>
<% provide(:class_text, 'add_base_point') %>
<% provide(:button_text, '拠点情報を追加する') %>
<h1>拠点情報の追加</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @base_point, local: true) do |f| %>
        <%#= render 'shared/error_messages' %>
        
        <%= f.label :base_point_number, class: "label-#{yield(:class_text)}" %>
        <%= f.text_field :base_point_number, class: "form-control" %>
        
        <%= f.label :base_point_name, class: "label-#{yield(:class_text)}" %>
        <%= f.text_field :base_point_name, class: "form-control" %>
        
        <%= f.label :base_point_type, class: "label-#{yield(:class_text)}" %><br />
        <%= f.select :base_point_type,[["出勤中"],["退勤"]] ,class: "form-control" %>
        
        <%= f.submit "#{yield(:button_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
    </div>
</div>