config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/sindex', to: 'users#sindex'
  
  # ログイン情報
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/overtime_application'
      patch 'attendances/update_overtime'
      get 'attendances/overtime_application_approval'
      patch 'attendances/update_overtime_approval'
      patch 'attendances/update_attendances_application'
      get 'attendances/attendances_application_approval'
      patch 'attendances/update_attendances_application_approval'
      patch 'attendances/update_attendances_change'
      get 'attendances/attendances_change_approval'
      patch 'attendances/update_attendances_change_approval'
      get 'attendances/attendances_change_history_log'
    end
    resources :attendances, only: [:update]
    collection { post :import }
  end

  resources :base_points
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :attendances, dependent: :destroy
    # 「remember_token」
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX= /\A[\w\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 100 },        format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
    validates :department, length: { in: 2..30}, allow_blank: true
    validates :basic_time, presence: true
    validates :work_time, presence: true
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, allow_nil: true
    
    
    # 渡された文字列のハッシュ値を返す。
    def User.digest(string)
        cost =
            if ActiveModel::SecurePassword.min_cost
                BCrypt::Engine::MIN_COST
            else
                BCrypt::Engine.cost
            end
        BCrypt::Password.create(string, cost: cost)
    end
    
    # ランダムなトークンを返す。
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # 永続セッションのためハッシュ化したトークンを
    # データベースに記憶する。
    
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # トークンがダイジェストと一致すればtrueを返します。
    def authenticated?(remember_token)
        # ダイジェストが存在しない場合はfalseを返して終了します。
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    # ユーザーのログイン情報を破棄します。
    def forget
        update_attribute(:remember_digest, nil)
    end

    #importメソッド
    def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save
        end
    end
    
    # 更新を許可するカラムを定義
    def self.updatable_attributes
        ["name", "email", "password" , "affiliation","employee_number","uid","basic_work_time","designated_work_start_time","designated_work_end_time","superior","admin"]
    end
end

app/controllers/users_controller.rb
require 'csv'
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:sindex, :index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info ]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :admin_user, only:[:destroy, :edit_basic_info, :update_basic_info, :index, :sindex]
  before_action :admin_user?, only:[:show]
  before_action :set_one_month, only:[:show ]
  
  def index
    @users = User.paginate(page: params[:page])
    
    @users = @users.where('name LIKE ?', "%#{params[:sword]}%") if params[:sword].present?
  end

  def sindex
    @users = User.all
    #debugger
  end

  def import
    if params[:file]
    User.import(params[:file])
    flash[:success] = "CSVをインポートしました"
    else
      flash[:danger] = "CSVを選択してください"
    end
    redirect_to users_url
  end
  
  def search_user
    @susers = params[:sword]
  end
  
  def new
    @user = User.new #ユーザーオブジェクトを生成し、インスタンス変数に代入。
  end
  
  def show

    #debugger # インスタンス変数を定義した直後にこのメソッドが実行されます。
    @worked_sum = @attendances.where.not(started_at: nil).count

    respond_to do |format|
      format.html
      format.csv do |csv|
        send_attendances_csv(@attendances)
      end
    end

    @users = User.includes(:attendances)
    #debugger
    @countjyotyo_jyotyo_a = Attendance.where(instructor_confirmation_status: "申請中" , instructor_confirmation_stamp: "上長1").count
    #@aaa = @users.id(params[:id])
    @countjyotyo_jyotyo_b = Attendance.where(instructor_confirmation_status: "申請中" , instructor_confirmation_stamp: "上長2").count
    @countapproval_jyotyo_a = Attendance.where(month_attendances_approval_status: "申請中" , month_attendances_approval_stamp: "上長1").distinct.count(:month)
    @countapproval_jyotyo_b = Attendance.where(month_attendances_approval_status: "申請中" , month_attendances_approval_stamp: "上長2").distinct.count(:month)
    @countchange_jyotyo_a = Attendance.where(change_application_status: "申請中" , change_application_stamp: "上長1").count
    @countchange_jyotyo_b = Attendance.where(change_application_status: "申請中" , change_application_stamp: "上長2").count
    #debugger
    @user_now = User.find(params[:usernow]) if params[:usernow]
    #debugger
  end

  def send_attendances_csv(attendandes)
    csv_data = CSV.generate do |csv|
      header = %w(日付 出勤時間 退勤時間)
      csv << header

      @attendances.each do |attendance|
        unless attendance.change_application_status == "申請中"
        #debugger
          if attendance.started_at.present? && attendance.finished_at.present?
          values = [attendance.worked_on,attendance.started_at.strftime("%H:%M:%S"),attendance.finished_at.strftime("%H:%M:%S")]
          csv << values
          end
        end
      end

    end
    send_data(csv_data, filename: "attendances.csv")
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user #保存成功後、ログインする。
      flash[:success] ="新規作成に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
      if @user.update_attributes(user_params)
        flash[:success] = "ユーザー情報を更新しました。"
        redirect_to @user
      else
        render :edit
      end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
    # debugger
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  private
      def user_params
        params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
      end
      
      def basic_info_params
        params.require(:user).permit(:basic_time, :work_time, :name, :email, :affiliation, :employee_number, :uid, :password, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
      end
      
      # beforeフィルター
      
      # paramsハッシュからユーザーを取得する。
      def set_user
        @user = User.find(params[:id])
      end
      
      def set_user_
        @user = User.find(params[:user_id])
      end
      
      # ログイン済みのユーザーか確認する
      def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "ログインしてください。"
          redirect_to login_url
        end
      end
      
      # アクセスしたユーザーが現在ログインしているユーザーか調べる
      def correct_user
        #debugger
        if current_user.admin? || current_user.superior?
        else
          redirect_to(root_url) unless current_user?(@user)
        end
      end
      
      def admin_user
        redirect_to root_url unless current_user.admin?
      end

      def admin_user?
        redirect_to root_url if current_user.admin?
      end
end

app/helpers/users_helper.rb
module UsersHelper
    #勤怠基本情報指定のフォーマットで返します。
    def format_basic_info(time)
        format("%.2f", ((time.hour * 60) + time.min) / 60.0)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages' %>
    
    <%= f.label :name, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :name, class: "form-control" %>
    
    <%= f.label :email, class: "label-#{yield(:class_text)}" %>
    <%= f.email_field :email, class: "form-control" %>
    
    <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :affiliation, class: "form-control" %>
    
    <%= f.label :password, class: "label-#{yield(:class_text)}" %>
    <%= f.password_field :password, class: "form-control" %>
    
    <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    
    <%= f.submit "#{yield(:button_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title , "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title , "basic_info") %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>
<h1><%= @user.name %>の基本情報更新</h1>
<div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center btn-basic_info-edit">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:class_text, 'user--all') %>
<% if current_user.admin? && current_user.superior? %>
    <% if params[:sword].present? %>
    <h1>検索結果</h1>
    <% else %>
    <h1>ユーザー一覧</h1>
    <% end %>
<% else%>
    <h1>ユーザー一覧</h1>
<% end%>

<div class="col-md-12">
    <table class="col-md-12">
        <tbody>
            <tr>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    <%= form_tag import_users_path, multipart: true do %>
                    　<%= file_field_tag :file %>
                      <%= submit_tag "CSVをインポート", class: "btn  btn-primary btn-user--all--csv" %>
                    <% end %>
                </td>
            </tr>
        </tbody>
    </table>

    <table class="col-md-12">
        <thead>
            <tr>
            <td style="padding:10px 0;">
            </td>
            </tr>
        </thead>
            <% @users.each do |user| %>
            <% if !user.admin? %>
            <tr>
                <td><%= user.name %></td>
            </tr>
            <tr>
                <td><%= link_to "削除" , user, method: :delete, data: { confirm: "#{user.name}を削除してもよろしいですか？"}, class: "btn btn-primary btn_users" %></td>
            </tr>
            <tr>
                <td><%# link_to "編集", edit_basic_info_user_path(user), class: "btn btn-primary btn-rg btn-users" %>
                <p style="background-color:#f5f5f5;">
                <button class="btn btn-lg btn-primary  btn-user--all" type="button" data-toggle="collapse" data-target="#collapseExample-<%= user.id %>" aria-expanded="false" aria-controls="collapseExample-<%= user.id %>">
                編集
                </button>
                </p>
                <div class="collapse" id="collapseExample-<%= user.id %>">
                <div class="card card-body">

                <div class="col-md-12">
                    <%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
                        <%# render 'shared/error_messages', object: @user %>

                        <%= f.label :name, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :name, class: "form-control" %>

                        <%= f.label :email, class: "label-#{yield(:class_text)}" %>
                        <%= f.email_field :email, class: "form-control" %>

                        <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :affiliation, class: "form-control" %>

                        <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :employee_number, class: "form-control" %>

                        <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :uid, class: "form-control" %>

                        <%= f.label :password, class: "label-#{yield(:class_text)}" %>
                        <%= f.password_field :password, class: "form-control" %>

                        <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :basic_work_time, class: "form-control" %>

                        <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :designated_work_start_time, class: "form-control" %>

                        <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :designated_work_end_time, class: "form-control" %>

                        <div class="center btn-basic_info-edit">
                        <%= f.submit "編集する", class: "btn btn-primary active btn-block" %>
                        </div>
                    <% end %>
                    </div>
                </div>
                </div>
                </td>
            </tr>
            <% end %>
            <% end %>
    </table>
</div>




<% if current_user.admin? && current_user.superior? %>
    <div class="search_user">
        <%= form_with(url: users_path, method: :get ,local: true , class: "from-inline")  do |f| %>
                <%= f.label :sword, "検索ワード", class: "label-login form-inline" %>
                <%= f.text_field :sword, class: "form-cont mb-2" %>
                <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
    </div>
<% end %>

<% if current_user.admin? && current_user.superior? %>
<div class="col-md-10 col-md-offset-1">
    <%= will_paginate %>
    <table class="table table-condensed table-hover" id="table-users">
        <thead>
            <tr>
                <th>
                    <%= User.human_attribute_name :name %>
                </th>
            </tr>
        </thead>
        
        <% @users.each do |user| %>
            <tr>
                <td>
                    <%= link_to user.name, user %>
                    <% if current_user.admin? && !current_user?(user) %> | 
                        <%= link_to "基本情報編集", edit_basic_info_user_path(user) %> | 
                        <%= link_to "削除" , user, method: :delete, data: { confirm: "削除してもよろしいですか？"} %>
                    <% end %>
                </td>
                <td>
                </td>
            </tr>
        <% end %>
    </table>
    <%= will_paginate %>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/users/sindex.html.erb
<% provide(:title, 'All Users') %>
<% if current_user.admin? && current_user.superior? %>
    <% if params[:sword].present? %>
    <h1>検索結果</h1>
    <% else %>
    <h1>出勤中社員一覧</h1>
    <% end %>
<% else%>
    <h1>出勤中社員一覧</h1>
<% end%>
<% if current_user.admin? && current_user.superior? %>
<div class="col-md-12">
    <table>
        <tbody>
            <tr>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    <%= form_tag import_users_path, multipart: true do %>
                    　<%= file_field_tag :file %>
                      <%= submit_tag "CSVをインポート", class: "btn btn-primary" %>
                    <% end %>
                </td>
            </tr>
        </tbody>
    </table>

    <table>
        <thead>
            <tr>
            Example
            </tr>
        </thead>
            <% @users.each do |user| %>
            <% if !user.admin? %>
            <tr>
                <td><%= user.name %></td>
            </tr>
            <tr>
                <td><%= link_to "削除" , user, method: :delete, data: { confirm: "削除してもよろしいですか？"}, class: "btn btn-primary btn_users" %></td>
            </tr>
            <tr>
                <td><%# link_to "編集", edit_basic_info_user_path(user), class: "btn btn-primary btn-rg btn-users" %>
                <p>
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample-<%= user.id %>" aria-expanded="false" aria-controls="collapseExample-<%= user.id %>">
                編集
                </button>
                </p>
                <div class="collapse" id="collapseExample-<%= user.id %>">
                <div class="card card-body">

                <div class="col-md-6 col-md-offset-3">
                    <%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
                        <%# render 'shared/error_messages', object: @user %>

                        <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :basic_time, class: "form-control" %>

                        <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :work_time, class: "form-control" %>

                        <div class="center btn-basic_info-edit">
                        <%= f.submit "編集する", class: "btn btn-primary" %>
                        <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                            キャンセル
                        </button>
                        </div>
                    <% end %>
                    </div>
                </div>
                </div>
                </td>
            </tr>
            <% end %>
            <% end %>
    </table>
</div>
<% end %>



<% if current_user.admin? && current_user.superior? %>
    <div class="search_user">
        <%= form_with(url: users_path, method: :get ,local: true , class: "from-inline")  do |f| %>
                <%= f.label :sword, "検索ワード", class: "label-login form-inline" %>
                <%= f.text_field :sword, class: "form-cont mb-2" %>
                <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
    </div>
<% end %>


<div class="col-md-12">
    <table class="table table-condensed table-hover table-bordered user-table" id="table-susers">
        <thead>
            <tr>
            <th>
            <%= User.human_attribute_name :employee_number %>
            </th>
                <th>
                    <%= User.human_attribute_name :name %>
                </th>
            </tr>
        </thead>
        
        <% @users.each do |user| %>
        <% user.attendances.each do |day|%>
        <!--<tr><td>
        <%#= day.started_at %>
        </td></tr>-->
        <% if day.started_at.present? && day.finished_at.nil? && day.worked_on == Date.current %>
            <tr>
                <td>
                    <%= user.employee_number %>
                    <%# if current_user.admin? && !current_user?(user) %> <!-- | --> 
                        <%# link_to "基本情報編集", edit_basic_info_user_path(user) %> <!--| --> 
                        <%# link_to "削除" , user, method: :delete, data: { confirm: "削除してもよろしいですか？"} %>
                    <%# end %>
                </td>
                <td>
                    <%= user.name %>
                </td>
            </tr>
        <% end %>
        <% end %>
        <% end %>
    </table>
</div>

app/views/users/susers.html.erb
<% provide(:title, 'S Users') %>
<h1>検索結果</h1>

<div class="col-md-10 col-md-offset-1">
    <%= will_paginate %>
    <table class="table table-condensed table-hover" id="table-users">
        <thead>
            <tr>
                <th>
                    <%= User.human_attribute_name :name %>
                </th>
            </tr>
        </thead>
        
        <% @susers.each do |user| %>
            <tr>
                <td>
                    <%= link_to user.name, user %>
                </td>
                <td>
                    <% if current_user.admin? && !current_user?(user) %>
                        <%= link_to "削除" , user, method: :delete, data: { confirm: "削除してもよろしいですか？"}, class: "btn btn-danger" %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
    <%= will_paginate %>
</div>