config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/sindex', to: 'users#sindex'
  
  # ログイン情報
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/overtime_application'
      patch 'attendances/update_overtime'
      get 'attendances/overtime_application_approval'
      patch 'attendances/update_overtime_approval'
      patch 'attendances/update_attendances_application'
      get 'attendances/attendances_application_approval'
      patch 'attendances/update_attendances_application_approval'
      patch 'attendances/update_attendances_change'
      get 'attendances/attendances_change_approval'
      patch 'attendances/update_attendances_change_approval'
      get 'attendances/attendances_change_history_log'
    end
    resources :attendances, only: [:update]
    collection { post :import }
  end

  resources :base_points
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  
  # 退勤時間が存在しない場合、は無効

  validate :without_a_finished_at_or_started_at_invalid

  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid

  #退社時間もしくは出社時間のみ
  validate :only_change_time_started_or_change_time_finished

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def without_a_finished_at_or_started_at_invalid
    if worked_on < Date.current
      if !started_at.nil? && finished_at.blank?
        errors.add(:finished_at, "が必要です")
      end
    end
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end

  def only_change_time_started_or_change_time_finished
    #debugger
    if !change_application_stamp.blank?
      if change_application_next_day == 1

        if (change_application_started_time.hour * 60 + change_application_started_time.min) > ((change_application_finished_time.hour + 24) * 60 + change_application_finished_time.min)
        errors.add(:change_application_started_time, "より早い退勤時間は無効です1") 
        end
      elsif change_application_next_day == 0
        if (change_application_started_time.hour * 60 + change_application_started_time.min) > (change_application_finished_time.hour * 60 + change_application_finished_time.min)
        errors.add(:change_application_started_time, "より早い退勤時間は無効です2")
        #debugger
        end 
      end
    end
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :overtime_application, :update_overtime, :overtime_application_approval, :update_application, :update_overtime_approval, :update_attendances_application ,:attendances_application_approval ,:update_attendances_application_approval, :update_attendances_change, :attendances_change_approval,:update_attendances_change_approval, :attendances_change_history_log]
  before_action :logged_in_user, only: [:update, :edit_one_month, :overtime_application, :update_overtime, :overtime_application_approval, :update_application , :update_overtime_approval,:attendances_change_paramspplication_approval,:update_attendances_change_approval]
  before_action :admin_or_correct_user, onry: [:update, :edit_one_month, :update_one_month, :overtime_application, :update_overtime, :overtime_application_approval, 
  :update_overtime_approval, :update_application, :update_attendances_application ,:attendances_application_approval,:update_attendances_application_approval, :update_attendances_change, :attendances_change_approval, :attendances_change_history_log]
  before_action :set_one_month, only: [:edit_one_month, :overtime_application, :overtime_application_approval, :update_attendances_application ,:update_attendances_application_approval, :update_attendances_change_approval, :attendances_change_history_log, :update_attendances_change]
  before_action :admin_user?, only:[:edit_one_month]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    #debugger
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        @attendance.update_attributes(before_change_started_time: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        @attendance.update_attributes(before_change_finish_time: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end


  def edit_one_month
    @attendance= Attendance.new()
  end
  
        #if !item[:started_at].nil? && item[:finished_at].blank?
        
       # else
        #attendance = Attendance.find(id)
        #attendance.update_attributes!(item)
        #end
  
  
  def update_one_month
    ActiveRecord::Base.transaction do # トランザクションを開始
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
      end
    end
    flash[:success] = "1か月間の勤怠情報を更新しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] ="無効な入力データがあった為、更新をキャンセルされました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end

  def attendances_change_history_log
    @attendances = @user.attendances.where(change_application_status: "承認")
#debugger
  
    @y=Date.today.year
    @m=Date.today.month
    

    #@attendances=@user.attendances.where(change_application_status: "申請中") if 
    
    #@eday = params[:y] + "-" + "0" +params[:m] + "-30"
    #debugger

    if params[:y] && params[:m] 
      if params[:y] != "年" && params[:m]  != "月"
        @fday = params[:y] + "-" + "0" +params[:m] + "-01"
        @eday = @fday.to_date.end_of_month.to_s
        #debugger
        if @y = params[:y]
          if @m = params[:m]
          @attendances = @user.attendances.where(change_application_status: "承認", worked_on: @fday..@eday)
          end
        end
      end
    else
      #redirect_to attendances_attendances_change_history_log_user_path
    end
    
    

    
    
    #debugger
  end


  def update_attendances_change
    #debugger
    @count = 0
    ActiveRecord::Base.transaction do
    update_attendances_change_params.each do |id, item|
      attendance = Attendance.find(id)
      #debugger
        if update_attendances_change_params[id][:change_application_stamp].present?
            #if update_attendances_change_params[id][:change_application_note].blank?
            #  raise ActiveRecord::RecordInvalid
            #end
            if update_attendances_change_params[id]["change_application_finished_time(4i)"] == "" || update_attendances_change_params[id]["change_application_finished_time(5i)"] == "" 
              raise ActiveRecord::RecordInvalid
            else
            #@attendance = attendance
            attendance.update_attributes!(item)
            attendance.update(change_application_status: params[:change_application_status])
            # if update_attendances_change_params["125"]["change_application_finished_time(4i)"] == ""

            end
        else
          @count += 1
        end
        #end
          #@count += 1
    end
    if @count == @one_month.count
      raise ActiveRecord::RecordInvalid
    end 
    end
    flash[:success]="勤怠変更申請を行いました。"
    redirect_to attendances_edit_one_month_user_url
  rescue ActiveRecord::RecordInvalid
    #errors.add(:change_application_started_time, "より早い退勤時間は無効です2")
    #debugger
    #if @count == 0 
      #User.find(params[:id]).attendances.where(month: params[:date].to_date.month.to_s, change_application_stamp: "").count == @one_month.count
    flash[:danger]="入力データが無効です。"
    #else
    #flash[:success]="勤怠変更申請を行いました。"
    #end
    redirect_to attendances_edit_one_month_user_url
  end

  def attendances_change_approval
    @users_attendances_change_approval_jyotyo_a = User.where(id: Attendance.where(change_application_status: "申請中", change_application_stamp: "上長1").select(:user_id).order(nil))
    @users_attendances_change_approval_jyotyo_b = User.where(id: Attendance.where(change_application_status: "申請中", change_application_stamp: "上長2").select(:user_id).order(nil))
  end

  def update_attendances_change_approval
    update_attendances_change_apploval_params.each do |id, item|
      #debugger
      if params[:user][:attendances][id][:change_application_change] == "1"
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
      if update_attendances_change_apploval_params[id][:change_application_status] == "なし"
          attendance.update(change_application_started_time: nil, change_application_finished_time: nil, change_application_stamp: nil,change_application_note: nil, change_application_status: nil) 
      elsif update_attendances_change_apploval_params[id][:change_application_status] == "否認"
      
      else
        attendance.update(started_at: attendance.change_application_started_time)
        attendance.update(finished_at: attendance.change_application_finished_time)
        if attendance.before_change_started_time.nil?
          if attendance.started_at.present?
          attendance.update(before_change_started_time: attendance.started_at)
          end
        end
        if attendance.before_change_finish_time.nil?
          if attendance.finished_at.present?
            attendance.update(before_change_finish_time: attendance.finished_at)
          end
        end
      end

      end
    end
    redirect_to user_url
  end
  
  # 一か月分の勤怠 申請
  def update_attendances_application
    #debugger
    #@attendance = @user.attendances
    ActiveRecord::Base.transaction do
      if params[:attendance][:month_attendances_approval_stamp] == ""
      flash[:danger]="申請者を選択してください。"
      else
        @attendances.each do |at|
        #debugger
        at.update_attributes!(attendances_application_params)
        at.update(month: format("%02d", params[:date].to_date.month.to_s ) + User.find(at.user_id).uid)
        
        end
        flash[:success]="所属長承認を申請しました。"
      end
    end
    #debugger
    redirect_to @user
  end

  # 一か月分の勤怠 申請 確認
  def attendances_application_approval
    @month_check = ""
    @users_attendances_application_approval_jyotyo_a = User.where(id: Attendance.where(month_attendances_approval_status: "申請中", month_attendances_approval_stamp: "上長1").select(:user_id))
    @users_attendances_application_approval_jyotyo_b = User.where(id: Attendance.where(month_attendances_approval_status: "申請中", month_attendances_approval_stamp: "上長2").select(:user_id))
    #@attendances = Attendance.where(month_attendances_approval_status: "申請中").group(:month)
    #debugger
  end

  # 一か月分の勤怠 申請 承認
  def update_attendances_application_approval
    #@attendance = params[:user][:attendance][:month_attendances_approval_status]
    #debugger
    ActiveRecord::Base.transaction do
    update_attendances_application_params.each do |id, item|
      #attendance = Attendance.find(id)
      user = User.find(Attendance.find(id).user_id)#User.find(id: Attendance.find(id).user_id)
      userid= user.id
      #debugger
      user_month = Attendance.find(id).month
      #user_id = user[:id]
      #debugger
      @attendances = Attendance.where(month: user_month, user_id: userid)
      #@user= user.attendances
      #debugger
        @attendances.each do |at|
          if params[:user][:attendances][id][:month_attendances_approval_change] == "1"
            at.update_attributes!(item)
            at.update(month: nil)
            if update_attendances_application_params[id][:month_attendances_approval_status] == "なし"
              at.update(month_attendances_approval_status: nil, month_attendances_approval_change: nil, month_attendances_approval_stamp: nil, month: nil) 
            end
          end
        end
        
      
      #debugger
        #user.each do |u|
        #  u.attendances.whrer(month: params[:date].to_date.month)
        #end
    end
    end

    #@attendances.each do |at|
      #at.update_attributes!(update_attendances_application_params)

app/helpers/attendances_helper.rb
module AttendancesHelper

    TIME_00 = "00"
    TIME_15 = 15
    TIME_30 = 30
    TIME_45 = 45

    YEAR = "2021"
    MONTH = "6"
     
    def attendance_state(attendance)
        # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
        if Date.current == attendance.worked_on
            return '出勤' if attendance.started_at.nil?
            return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
        end
        # どれにも当てはまらなかった場合はfalseを返します。
        false
    end
    def time_fix(t)
        if t <= 59 && t >= 45
          TIME_45
        elsif t < 45 && t >= 30
          TIME_30
        elsif t < 30 && t >= 15
          TIME_15
        elsif t < 15 && t >= 0
          TIME_00
        end
    end  

    def user_no(u)
      u + 1
    end
    
    # 出勤時間と退勤時間を受け取り、在社時間を計算して返す。
    def working_time(start, finish)
      #debugger
        format("%.2f", (((finish - start) / 60) / 60.0))
    end

    def working_time_start_chage(start)
      #debugger
      start.hour.to_i * 60 + time_fix(start.min.to_i).to_i
    end

    def working_time_finish_chage(finish)
      #debugger
      finish.hour.to_i * 60 + time_fix(finish.min.to_i).to_i
    end

    def working_time_chage(start, finish)
      #debugger
      format("%.2f", ((finish - start) / 60.0))
    end

    def working_time_chage_next(start, finish)
      #debugger
      format("%.2f", ((((finish.hour.to_i + 24) * 60 + time_fix(finish.min.to_i).to_i) - start) / 60.0))
    end

    def over_time(over, finish)
      #debugger
        format("%.2f", ((over - finish) / 60.0))
    end

    def zangyo_time(overtime)
        overtime.hour.to_i * 60 + time_fix(overtime.min.to_i).to_i
    end

    def zangyo_time_next(overtime)
      (overtime.hour.to_i + 24) * 60 + time_fix(overtime.min.to_i).to_i
    end

    def syuryo_time(syuryotime)
        syuryotime.hour.to_i * 60 + time_fix(syuryotime.min.to_i).to_i
    end
end

app/views/attendances/_attendances_application_approval.html.erb
<% provide(:class_text, 'attendances-application-approval') %>
<% provide(:button_text, '変更を送信する') %>
<div class="modal-dialog modal-lg modal-dialog-center">
<%= form_with(model:@user , url: attendances_update_attendances_application_approval_user_path(@user,@attendances), local: true, method: :patch) do |f| %>
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <% if @user.name == "上長1" %>
    <% @users_attendances_application_approval_jyotyo_a.each do |user| %>
      <h1 class="modal-title"><%= user.name %>からの一か月分の勤怠申請</h1>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
           <table class="table table-bordered table-condensed table-hover" id="table-attendances">
            <thead>
                <tr>
                <th>月</th>
                <th>指示者確認印</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
                </tr>
            </thead>
            <tbody>
            <% user.attendances.each do |day| %>
            <% if @month_check != day.month %>
            <% @month_check = day.month if !day.month.nil? %>

            <%= f.fields_for "attendances[]",day do |attendance| %>
                <% if day.month_attendances_approval_status == "申請中" %>
                <%# debugger %>
                        <tr>
                        <%= attendance.hidden_field :ap_month, value: day.month %>
                        <td><%# debugger %>
                        <% if day.month.slice(0,2)[0] == "0" %>
                        <%= day.month.slice(1,1) %>
                        <% else %>
                        <%= day.month.slice(0,2) %>
                        <% end %>
                        月</td>
                        <td>
                        <%= attendance.label :month_attendances_approval_status, class: "label-#{yield(:class_text)} hidden" %>
                        <%= attendance.select :month_attendances_approval_status,[["なし"],["申請中"],["承認"],["否認"]] ,class: "form-control" %>
                        </td>
                        <td><%= attendance.label :month_attendances_approval_change, class: "check_box inline checkbox-over_time_application", for: "month_attendances_approval_change" do %>
                            <%= attendance.check_box :month_attendances_approval_change, checked: false, id: "month_attendances_approval_change" %>
                        <% end %></td>
                        <td><%= link_to "確認", user_path(user, usernow: @user.id), class: "btn btn-primary" %></td>
                        </tr>
                <% end %>
                <% end %>
              <% end %>
            <% end %>
            </tbody>
            </table>
        </div>
        <div class="clearfix"></div>
      <% end %>
      <% end %>

<% if @user.name == "上長2" %>
    <% @users_attendances_application_approval_jyotyo_b.each do |user| %>
      <h1 class="modal-title"><%= user.name %>からの一か月分の勤怠申請</h1>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
           <table class="table table-bordered table-condensed table-hover" id="table-attendances">
            <thead>
                <tr>
                <th>月</th>
                <th>指示者確認印</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
                </tr>
            </thead>
            <tbody>
            <% user.attendances.each do |day| %>
              <% if @month_check != day.month %>
              <% @month_check = day.month if !day.month.nil? %>
              <%= f.fields_for "attendances[]",day do |attendance| %>
                <% if day.month_attendances_approval_status == "申請中" %>
                        <tr>
                        <%= attendance.hidden_field :ap_month, value: day.month %>
                        <td>
                        <%# debugger %>
                        <% if day.month.slice(0,2)[0] == "0" %>
                        <%= day.month.slice(1,1) %>
                        <% else %>
                        <%= day.month.slice(0,2) %>
                        <% end %>
                        月</td>
                        <td>
                        <%= attendance.label :month_attendances_approval_status, class: "label-#{yield(:class_text)} hidden" %>
                        <%= attendance.select :month_attendances_approval_status,[["なし"],["申請中"],["承認"],["否認"]] ,class: "form-control" %>
                        </td>
                        <td><%= attendance.label :month_attendances_approval_change, class: "check_box inline checkbox-over_time_application", for: "month_attendances_approval_change" do %>
                            <%= attendance.check_box :month_attendances_approval_change, checked: false, id: "month_attendances_approval_change" %>
                        <% end %></td>
                        <td><%= link_to "確認", user_path(user, usernow: @user.id), class: "btn btn-primary" %></td>
                        </tr>
                  <% end %>
              <% end %>
              <% end %>




            <% end %>
            </tbody>
            </table>
        </div>
        <div class="clearfix"></div>
      <% end %>
      <% end %>


      </div>
      <div class="center">
    <%= f.submit "#{yield(:button_text)}", class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/attendances/_attendances_change_approval.html.erb
<% provide(:class_text, 'attendances-change-approval') %>
<% provide(:button_text, '変更を送信する') %>
<div class="modal-dialog modal-lg modal-dialog-center">
<%= form_with(model:@user , url: attendances_update_attendances_change_approval_user_path(@user,@attendances), local: true, method: :patch) do |f| %>
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <% if current_user.name == "上長1" %>
    <% @users_attendances_change_approval_jyotyo_a.each do |user| %>
      <h1 class="modal-title"><%= user.name %>からの勤怠変更申請</h1>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
           <table class="table table-bordered table-condensed table-hover" id="table-attendances">
            <thead>
                <tr>
                    <th colspan="2" rowspan="2"></th>
                    
                    <th colspan="4">変更前</th>
                    
                    <th colspan="4">変更後</th>
                    
                    <th colspan="4" rowspan="2"></th>
                    
                </tr>
                <tr>
                    
                    <th colspan="2">出社</th>
                    
                    <th colspan="2">退社</th>
                    
                    <th colspan="2">出社</th>
                    
                    <th colspan="2">退社</th>
                    
                
                </tr>
                <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>備考</th>
                <th>支持者確認印</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
                </tr>
            </thead>
            <tbody>
            
            <% user.attendances.each do |day| %>
            <%# debugger %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                <% if day.change_application_status == "申請中" %>
                        <tr>
                        <%= attendance.hidden_field :change_application_status, :value => "承認" %>

                        <td><%= l(day.worked_on, format: :short) %></td>
                        
                        <td><%= $days_of_the_week[day.worked_on.wday] %> </td>
                        
                        <td><%= l(day.before_change_started_time, format: :time_h).to_i if day.before_change_started_time.present? %></td>

                        <td>
                        <%= time_fix(l(day.before_change_started_time, format: :time_m).to_i) if day.before_change_started_time.present? %>
                        </td>

                        <td><%= l(day.before_change_finish_time, format: :time_h).to_i if day.before_change_finish_time.present? %></td>

                        <td>
                        <%= time_fix(l(day.before_change_finish_time, format: :time_m).to_i) if day.before_change_finish_time.present? %>
                        </td>
                        
                        <td><%= l(day.change_application_started_time, format: :time_h).to_i if day.change_application_started_time.present? %></td>

                        <td>
                        <%= time_fix(l(day.change_application_started_time, format: :time_m).to_i) if day.change_application_finished_time.present? %>
                        </td>

                        <td><%= l(day.change_application_finished_time, format: :time_h).to_i if day.change_application_started_time.present? %></td>
                        
                        <td>
                        <%= time_fix(l(day.change_application_finished_time, format: :time_m).to_i) if day.change_application_finished_time.present? %>
                        </td>

                        <td>
                        <%= day.change_application_note %>
                        </td>
                        <td>
                        <%= attendance.label :change_application_status, class: "label-#{yield(:class_text)} hidden" %>
                        <%= attendance.select :change_application_status,[["なし"],["申請中"],["承認"],["否認"]] ,class: "form-control" %>
                        </td>
                        <td><%= attendance.label :change_application_change, class: "check_box inline checkbox-over_time_application", for: "next_day" do %>
                            <%= attendance.check_box :change_application_change, checked: false, id: "change_application_change" %>
                        <% end %></td>
                        <td><%= link_to "確認", user_path(user, usernow: @user.id), class: "btn btn-primary" %></td>
                        </tr>
                        <% end %>
                        <% end %>
                        <% end %>
            </tbody>
            </table>
        </div>
        <div class="clearfix"></div>
      <% end %>
      <% end %>


    <% if current_user.name == "上長2" %>
    <% @users_attendances_change_approval_jyotyo_b.each do |user| %>
      <h1 class="modal-title"><%= user.name %>からの勤怠変更申請</h1>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
           <table class="table table-bordered table-condensed table-hover" id="table-attendances">
            <thead>
                <tr>
                    <th colspan="2" rowspan="2"></th>
                    
                    <th colspan="4">変更前</th>
                    
                    <th colspan="4">変更後</th>
                    
                    <th colspan="4" rowspan="2"></th>
                    
                </tr>
                <tr>
                    
                    <th colspan="2">出社</th>
                    
                    <th colspan="2">退社</th>
                    
                    <th colspan="2">出社</th>
                    
                    <th colspan="2">退社</th>
                    
                
                </tr>
                <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>備考</th>
                <th>支持者確認印</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
                </tr>
            </thead>
            <tbody>
            
            <% user.attendances.each do |day| %>
            <%# debugger %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                <% if day.change_application_status == "申請中" %>
                
                        <tr>
                        <%= attendance.hidden_field :change_application_status, :value => "承認" %>

                        <td><%= l(day.worked_on, format: :short) %></td>
                        
                        <td><%= $days_of_the_week[day.worked_on.wday] %> </td>
                        
                        <td><%= l(day.before_change_started_time, format: :time_h).to_i if day.before_change_started_time.present? %></td>

                        <td>
                        <%= time_fix(l(day.before_change_started_time, format: :time_m).to_i) if day.before_change_started_time.present? %>
                        </td>

                        <td><%= l(day.before_change_finish_time, format: :time_h).to_i if day.before_change_finish_time.present? %></td>

                        <td>
                        <%= time_fix(l(day.before_change_finish_time, format: :time_m).to_i) if day.before_change_finish_time.present? %>
                        </td>
                        
                        <td><%= l(day.change_application_started_time, format: :time_h).to_i if day.change_application_started_time.present? %></td>

                        <td>
                        <%= time_fix(l(day.change_application_started_time, format: :time_m).to_i) if day.change_application_finished_time.present? %>
                        </td>

                        <td><%= l(day.change_application_finished_time, format: :time_h).to_i if day.change_application_started_time.present? %></td>
                        
                        <td>
                        <%= time_fix(l(day.change_application_finished_time, format: :time_m).to_i) if day.change_application_finished_time.present? %>
                        </td>

                        <td>
                        <%= day.change_application_note %>
                        </td>
                        <td>
                        <%= attendance.label :change_application_status, class: "label-#{yield(:class_text)} hidden" %>
                        <%= attendance.select :change_application_status,[["なし"],["申請中"],["承認"],["否認"]] ,class: "form-control" %>
                        </td>
                        <td><%= attendance.label :change_application_change, class: "check_box inline checkbox-over_time_application", for: "next_day" do %>
                            <%= attendance.check_box :change_application_change, checked: false, id: "change_application_change" %>
                        <% end %></td>
                        <td><%= link_to "確認", user_path(user, usernow: @user.id), class: "btn btn-primary" %></td>
                        </tr>
                        <% end %>
                        <% end %>
                        <% end %>
            </tbody>
            </table>
        </div>
        <div class="clearfix"></div>
      <% end %>
      <% end %>
      </div>
      <div class="center">
    <%= f.submit "#{yield(:button_text)}", class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/attendances/attendances_application_approval.js.erb
$("#attendances-application-approval").html("<%= escape_javascript(render 'attendances_application_approval') %>");
$("#attendances-application-approval").modal("show");

app/views/attendances/attendances_change_approval.js.erb
$("#attendances-change-approval").html("<%= escape_javascript(render 'attendances_change_approval') %>");
$("#attendances-change-approval").modal("show");

app/views/attendances/overtime_application.js.erb
$("#overtime-application").html("<%= escape_javascript(render 'overtime_application') %>");
$("#overtime-application").modal("show");

app/views/attendances/overtime_application_approval.js.erb
$("#overtime-application-approval").html("<%= escape_javascript(render 'overtime_application_approval') %>");
$("#overtime-application-approval").modal("show");